// Non-destructive, additive companion to prisma/seed.ts's "Bulk curriculum
// expansion" block. Run this against a database that already has the
// existing seed data (subjects, grades, the school admin user) instead of
// prisma migrate reset --force, so an already-live database — including
// one a production deployment reads from — never gets wiped just to add
// more lesson content. Safe to run once; re-running would create
// duplicate lessons (the existence check below only skips titles already
// present, so don't run it twice without checking first).
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type BulkLesson = {
  subjectCode: string;
  gradeName: string;
  unitTitle: string;
  lessonTitle: string;
  vocabulary: string[];
  explanation: string;
  sentences: string[];
  isStory: boolean;
  quizPrompt: string;
  options: { label: string; correct: boolean }[];
  recommendedAge: string;
};

const GRADE_NAME: Record<string, string> = {
  PREKINDER: "Pre-Kínder", KINDER: "Kínder", PREPRIMARIO: "Preprimario",
  P1: "1er Grado", P2: "2do Grado", P3: "3er Grado", P4: "4to Grado", P5: "5to Grado", P6: "6to Grado",
  S1: "1er Año de Secundaria", S2: "2do Año de Secundaria", S3: "3er Año de Secundaria",
  S4: "4to Año de Secundaria", S5: "5to Año de Secundaria", S6: "6to Año de Secundaria",
};
const RECOMMENDED_AGE: Record<string, string> = {
  PREKINDER: "3-4 años", KINDER: "4-5 años", PREPRIMARIO: "5-6 años",
  P1: "6-7 años", P2: "7-8 años", P3: "8-9 años", P4: "9-10 años", P5: "10-11 años", P6: "11-12 años",
  S1: "12-13 años", S2: "13-14 años", S3: "14-15 años", S4: "15-16 años", S5: "16-17 años", S6: "17-18 años",
};
const STORY_GRADES = new Set(["PREKINDER", "KINDER", "PREPRIMARIO"]);

const RAW: { subjectKey: string; gradeKey: string; unitTitle: string; lessonTitle: string; vocabulary: string[]; explanation: string; sentences: string[]; quizPrompt: string; options: { label: string; correct: boolean }[] }[] = [
  { subjectKey: "SPANISH", gradeKey: "P3", unitTitle: "Vocabulario", lessonTitle: "Los sinónimos", vocabulary: ["sinónimo", "feliz", "contento"], explanation: "Los estudiantes aprenden qué es un sinónimo con ejemplos cotidianos.", sentences: ["Un sinónimo es una palabra que significa casi lo mismo que otra.", "Por ejemplo, feliz y contento son sinónimos.", "Grande y enorme también son sinónimos.", "Usar sinónimos ayuda a que nuestros cuentos sean más interesantes."], quizPrompt: "¿Cuál palabra es sinónimo de 'feliz'?", options: [{ label: "Contento", correct: true }, { label: "Triste", correct: false }, { label: "Cansado", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "P4", unitTitle: "Gramática", lessonTitle: "Tipos de oraciones", vocabulary: ["afirmativa", "negativa", "interrogativa"], explanation: "Introducción a los tipos básicos de oraciones según su intención.", sentences: ["Una oración puede ser afirmativa, negativa o interrogativa.", "'El perro corre' es una oración afirmativa.", "'El perro no corre' es una oración negativa.", "'¿El perro corre?' es una oración interrogativa."], quizPrompt: "¿Qué tipo de oración es '¿Vienes a jugar?'?", options: [{ label: "Interrogativa", correct: true }, { label: "Negativa", correct: false }, { label: "Afirmativa", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "P5", unitTitle: "Narrativa", lessonTitle: "El cuento y sus partes", vocabulary: ["inicio", "desarrollo", "final"], explanation: "Estructura básica de un cuento: inicio, desarrollo y final.", sentences: ["Todo cuento tiene inicio, desarrollo y final.", "En el inicio conocemos a los personajes y el lugar.", "En el desarrollo ocurre el problema de la historia.", "En el final el problema se resuelve."], quizPrompt: "¿En qué parte del cuento se resuelve el problema?", options: [{ label: "El final", correct: true }, { label: "El inicio", correct: false }, { label: "El desarrollo", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "P6", unitTitle: "Géneros textuales", lessonTitle: "Biografías breves", vocabulary: ["biografía", "investigar"], explanation: "Qué es una biografía y para qué sirve.", sentences: ["Una biografía cuenta la vida de una persona real.", "Incluye dónde y cuándo nació, y lo que hizo de importante.", "Las biografías nos ayudan a conocer la historia a través de las personas.", "Escribir una biografía requiere investigar datos verdaderos."], quizPrompt: "¿Qué cuenta una biografía?", options: [{ label: "La vida de una persona real", correct: true }, { label: "Una historia inventada", correct: false }, { label: "Una receta de cocina", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S1", unitTitle: "Literatura", lessonTitle: "Los géneros literarios", vocabulary: ["narrativa", "poesía", "teatro"], explanation: "Panorama de los tres grandes géneros literarios.", sentences: ["Los géneros literarios son formas de clasificar los textos según su estilo.", "La narrativa cuenta historias, como los cuentos y las novelas.", "La poesía usa el ritmo y las imágenes para expresar emociones.", "El teatro se escribe para ser representado por actores."], quizPrompt: "¿Qué género literario se escribe para ser representado por actores?", options: [{ label: "El teatro", correct: true }, { label: "La poesía", correct: false }, { label: "La narrativa", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S2", unitTitle: "Redacción", lessonTitle: "El ensayo", vocabulary: ["ensayo", "argumento", "conclusión"], explanation: "Estructura y propósito del ensayo como género de opinión.", sentences: ["El ensayo es un texto donde el autor expresa su opinión sobre un tema.", "Un buen ensayo presenta una idea principal y la respalda con argumentos.", "El ensayo suele tener introducción, desarrollo y conclusión.", "Escribir ensayos ayuda a organizar y defender nuestras ideas."], quizPrompt: "¿Qué expresa principalmente un ensayo?", options: [{ label: "La opinión del autor sobre un tema", correct: true }, { label: "Solo datos sin opinión", correct: false }, { label: "Una lista de personajes", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S3", unitTitle: "Literatura dominicana", lessonTitle: "La literatura dominicana", vocabulary: ["identidad", "tradición"], explanation: "Panorama general de la literatura dominicana y su relación con la identidad nacional.", sentences: ["La literatura dominicana incluye poesía, cuentos y novelas escritos por autores del país.", "A través de los años, muchos escritores dominicanos han contado historias sobre la identidad nacional.", "La literatura dominicana refleja la cultura, la historia y las tradiciones de la isla.", "Leer autores dominicanos nos ayuda a conocer mejor nuestra propia cultura."], quizPrompt: "¿Qué refleja la literatura dominicana?", options: [{ label: "La cultura y la historia del país", correct: true }, { label: "Solo cuentos de otros países", correct: false }, { label: "Únicamente temas de matemáticas", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S4", unitTitle: "Redacción avanzada", lessonTitle: "Técnicas de redacción", vocabulary: ["párrafo", "conector", "claridad"], explanation: "Técnicas para organizar ideas y mejorar la claridad de un texto.", sentences: ["Una buena redacción organiza las ideas de forma clara y ordenada.", "Cada párrafo debe desarrollar una sola idea principal.", "Revisar y corregir el texto mejora la claridad del mensaje.", "Usar conectores como 'además' o 'sin embargo' ayuda a unir las ideas."], quizPrompt: "¿Qué debe desarrollar cada párrafo?", options: [{ label: "Una sola idea principal", correct: true }, { label: "Varias ideas sin orden", correct: false }, { label: "Ninguna idea concreta", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S5", unitTitle: "Comprensión lectora", lessonTitle: "Análisis de textos", vocabulary: ["tema", "tono", "propósito"], explanation: "Cómo analizar el mensaje, la estructura y la intención de un texto.", sentences: ["Analizar un texto significa comprender su mensaje, estructura e intención.", "Se debe identificar el tema principal y los argumentos que lo sostienen.", "También es importante notar el tono y el propósito del autor.", "El análisis de textos mejora la comprensión lectora."], quizPrompt: "¿Qué se identifica al analizar un texto?", options: [{ label: "El tema principal y sus argumentos", correct: true }, { label: "Solo el número de páginas", correct: false }, { label: "El color de la portada", correct: false }] },
  { subjectKey: "SPANISH", gradeKey: "S6", unitTitle: "Comunicación", lessonTitle: "Comunicación oral y debate", vocabulary: ["debate", "postura", "argumento"], explanation: "Habilidades para comunicarse oralmente y participar en un debate con respeto.", sentences: ["La comunicación oral efectiva requiere hablar con claridad y escuchar con atención.", "En un debate, cada participante defiende su postura con argumentos y respeto.", "Es importante escuchar otros puntos de vista antes de responder.", "Practicar la comunicación oral prepara para la vida universitaria y laboral."], quizPrompt: "¿Qué se debe hacer antes de responder en un debate?", options: [{ label: "Escuchar el punto de vista del otro", correct: true }, { label: "Interrumpir de inmediato", correct: false }, { label: "Ignorar al otro participante", correct: false }] },

  { subjectKey: "MATH", gradeKey: "KINDER", unitTitle: "Números", lessonTitle: "Contar hasta 10", vocabulary: ["contar", "número"], explanation: "Conteo del uno al diez usando los dedos como apoyo.", sentences: ["Podemos contar del uno al diez usando los dedos de las manos.", "Uno, dos, tres, cuatro, cinco…", "Seis, siete, ocho, nueve, diez.", "Contar nos ayuda a saber cuántas cosas tenemos."], quizPrompt: "¿Qué número viene después del 7?", options: [{ label: "8", correct: true }, { label: "6", correct: false }, { label: "10", correct: false }] },
  { subjectKey: "MATH", gradeKey: "P5", unitTitle: "Números decimales", lessonTitle: "Los números decimales", vocabulary: ["decimal", "punto decimal"], explanation: "Qué es un número decimal y cómo se identifica su parte entera y decimal.", sentences: ["Un número decimal tiene una parte entera y una parte decimal separadas por un punto.", "Por ejemplo, en 3.5 el 3 es la parte entera y el 5 es la parte decimal.", "Los decimales se usan para representar cantidades que no son números completos.", "Podemos sumar y restar decimales igual que los números enteros."], quizPrompt: "En el número 4.7, ¿cuál es la parte decimal?", options: [{ label: "7", correct: true }, { label: "4", correct: false }, { label: "47", correct: false }] },
  { subjectKey: "MATH", gradeKey: "P6", unitTitle: "Porcentajes", lessonTitle: "Los porcentajes", vocabulary: ["porcentaje", "por ciento"], explanation: "Introducción al concepto de porcentaje y su uso cotidiano.", sentences: ["Un porcentaje representa una parte de cien.", "El símbolo % significa 'por ciento'.", "Si 50 de 100 estudiantes tienen un lápiz, eso es el 50%.", "Los porcentajes se usan todos los días, como en descuentos de tiendas."], quizPrompt: "¿Qué significa el símbolo %?", options: [{ label: "Por ciento", correct: true }, { label: "Por mil", correct: false }, { label: "Por diez", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S1", unitTitle: "Álgebra", lessonTitle: "Ecuaciones lineales simples", vocabulary: ["ecuación", "incógnita", "despejar"], explanation: "Resolución de ecuaciones lineales sencillas con una incógnita.", sentences: ["Una ecuación lineal tiene una incógnita, generalmente representada con la letra x.", "Para resolverla, despejamos x hasta dejarla sola en un lado de la igualdad.", "Por ejemplo, en x + 3 = 8, restamos 3 en ambos lados para obtener x = 5.", "Practicar ecuaciones ayuda a desarrollar el pensamiento lógico."], quizPrompt: "Si x + 4 = 10, ¿cuánto vale x?", options: [{ label: "6", correct: true }, { label: "14", correct: false }, { label: "4", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S2", unitTitle: "Geometría", lessonTitle: "Perímetro y área", vocabulary: ["perímetro", "área"], explanation: "Diferencia entre perímetro y área, con el ejemplo del rectángulo.", sentences: ["El perímetro es la suma de todos los lados de una figura.", "El área mide el espacio que ocupa una figura en el plano.", "Para un rectángulo, el área se calcula multiplicando base por altura.", "Perímetro y área se usan para medir terrenos y construcciones."], quizPrompt: "¿Cómo se calcula el área de un rectángulo?", options: [{ label: "Base por altura", correct: true }, { label: "Base más altura", correct: false }, { label: "Base menos altura", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S3", unitTitle: "Razones y proporciones", lessonTitle: "Razones y proporciones", vocabulary: ["razón", "proporción"], explanation: "Qué son las razones y proporciones y cómo se usan.", sentences: ["Una razón compara dos cantidades, como 2 a 3.", "Una proporción indica que dos razones son iguales.", "Las proporciones se usan para hacer recetas más grandes o pequeñas.", "Resolver proporciones ayuda a comparar cantidades de forma justa."], quizPrompt: "¿Qué indica una proporción?", options: [{ label: "Que dos razones son iguales", correct: true }, { label: "Que dos números son diferentes", correct: false }, { label: "Que un número es negativo", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S4", unitTitle: "Funciones", lessonTitle: "Funciones básicas", vocabulary: ["función", "valor de entrada", "valor de salida"], explanation: "Introducción al concepto de función matemática.", sentences: ["Una función relaciona cada valor de entrada con un único valor de salida.", "Se puede representar con una fórmula, como y = 2x.", "Las funciones se usan para modelar situaciones de la vida real.", "Graficar una función ayuda a visualizar su comportamiento."], quizPrompt: "En la función y = 2x, si x = 3, ¿cuánto vale y?", options: [{ label: "6", correct: true }, { label: "5", correct: false }, { label: "9", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S5", unitTitle: "Estadística", lessonTitle: "Estadística: el promedio", vocabulary: ["promedio", "media", "dato"], explanation: "Cómo calcular e interpretar el promedio de un conjunto de datos.", sentences: ["El promedio, o media, se calcula sumando todos los valores y dividiendo entre la cantidad de datos.", "Por ejemplo, el promedio de 4, 6 y 8 es 6.", "El promedio ayuda a resumir un conjunto de datos con un solo número.", "Se usa en calificaciones, deportes y muchas áreas de la vida diaria."], quizPrompt: "¿Cuál es el promedio de 2, 4 y 6?", options: [{ label: "4", correct: true }, { label: "6", correct: false }, { label: "2", correct: false }] },
  { subjectKey: "MATH", gradeKey: "S6", unitTitle: "Finanzas personales", lessonTitle: "Finanzas personales básicas", vocabulary: ["presupuesto", "ahorro"], explanation: "Conceptos básicos de presupuesto y ahorro para la vida adulta.", sentences: ["Un presupuesto es un plan para organizar los ingresos y los gastos.", "Ahorrar significa guardar una parte del dinero para el futuro.", "Comparar precios antes de comprar ayuda a gastar de forma inteligente.", "Entender las finanzas personales prepara para tomar buenas decisiones económicas."], quizPrompt: "¿Qué es un presupuesto?", options: [{ label: "Un plan para organizar ingresos y gastos", correct: true }, { label: "Un tipo de préstamo", correct: false }, { label: "Un impuesto obligatorio", correct: false }] },

  { subjectKey: "SCIENCE", gradeKey: "PREKINDER", unitTitle: "Mi cuerpo", lessonTitle: "Mis cinco sentidos", vocabulary: ["ver", "oír", "oler", "sentir"], explanation: "Los cinco sentidos y para qué sirve cada uno.", sentences: ["Con los ojos vemos los colores y las formas.", "Con los oídos escuchamos la música y las voces.", "Con la nariz olemos las flores y la comida.", "Con la piel sentimos si algo está frío o caliente."], quizPrompt: "¿Con qué parte del cuerpo escuchamos?", options: [{ label: "Los oídos", correct: true }, { label: "Los ojos", correct: false }, { label: "La nariz", correct: false }] },
  { subjectKey: "SCIENCE", gradeKey: "KINDER", unitTitle: "Los animales", lessonTitle: "Los animales de la granja", vocabulary: ["vaca", "gallina", "caballo"], explanation: "Animales comunes de la granja y los sonidos o productos que dan.", sentences: ["La vaca nos da leche y dice 'muu'.", "La gallina pone huevos y dice 'clo clo'.", "El caballo corre rápido por el campo.", "En la granja viven muchos animales que nos ayudan."], quizPrompt: "¿Qué animal nos da leche?", options: [{ label: "La vaca", correct: true }, { label: "La gallina", correct: false }, { label: "El caballo", correct: false }] },
  { subjectKey: "SCIENCE", gradeKey: "PREPRIMARIO", unitTitle: "El agua", lessonTitle: "El ciclo del agua", vocabulary: ["vapor", "nube", "lluvia"], explanation: "Las etapas básicas del ciclo del agua.", sentences: ["El sol calienta el agua del mar y la convierte en vapor.", "El vapor sube al cielo y forma las nubes.", "Cuando las nubes se llenan, cae la lluvia.", "El agua de lluvia vuelve a los ríos y al mar."], quizPrompt: "¿Qué forma las nubes en el cielo?", options: [{ label: "El vapor de agua", correct: true }, { label: "Las piedras", correct: false }, { label: "El viento solo", correct: false }] },
  { subjectKey: "SCIENCE", gradeKey: "P1", unitTitle: "Las plantas", lessonTitle: "Las partes de una planta", vocabulary: ["raíz", "tallo", "hoja", "flor"], explanation: "Las partes principales de una planta y su función.", sentences: ["La raíz sostiene la planta y absorbe agua del suelo.", "El tallo sostiene las hojas y las flores.", "Las hojas usan la luz del sol para producir alimento.", "Las flores producen las semillas de nuevas plantas."], quizPrompt: "¿Qué parte de la planta absorbe agua del suelo?", options: [{ label: "La raíz", correct: true }, { label: "La flor", correct: false }, { label: "La hoja", correct: false }] },
  { subjectKey: "SCIENCE", gradeKey: "P2", unitTitle: "El cuerpo humano", lessonTitle: "El cuerpo humano", vocabulary: ["corazón", "pulmones", "huesos"], explanation: "Órganos principales del cuerpo humano y su función básica.", sentences: ["El corazón bombea la sangre por todo el cuerpo.", "Los pulmones nos ayudan a respirar aire.", "Los huesos forman el esqueleto que sostiene el cuerpo.", "Los músculos nos permiten movernos."], quizPrompt: "¿Qué órgano bombea la sangre?", options: [{ label: "El corazón", correct: true }, { label: "Los pulmones", correct: false }, { label: "Los huesos", correct: false }] },
  { subjectKey: "SCIENCE", gradeKey: "P6", unitTitle: "El universo", lessonTitle: "El sistema solar", vocabulary: ["sistema solar", "planeta", "Tierra"], explanation: "Introducción al sistema solar y la posición de la Tierra.", sentences: ["El sistema solar está formado por el Sol y los planetas que giran a su alrededor.", "La Tierra es el tercer planeta desde el Sol.", "Cada planeta tarda un tiempo diferente en dar una vuelta completa al Sol.", "Los astronautas estudian el espacio para aprender más sobre el sistema solar."], quizPrompt: "¿Qué planeta es el tercero desde el Sol?", options: [{ label: "La Tierra", correct: true }, { label: "Marte", correct: false }, { label: "Júpiter", correct: false }] },

  { subjectKey: "SOCIAL", gradeKey: "PREKINDER", unitTitle: "Mi familia", lessonTitle: "Mi familia", vocabulary: ["familia", "cuidar"], explanation: "El concepto de familia y su importancia.", sentences: ["Mi familia está formada por las personas que me cuidan y me quieren.", "Cada familia es diferente y especial.", "En mi familia compartimos comidas y momentos felices.", "Es importante respetar y ayudar a nuestra familia."], quizPrompt: "¿Qué hacemos en familia?", options: [{ label: "Compartir momentos felices", correct: true }, { label: "Ignorarnos", correct: false }, { label: "Pelear siempre", correct: false }] },
  { subjectKey: "SOCIAL", gradeKey: "KINDER", unitTitle: "Mi comunidad", lessonTitle: "Mi comunidad", vocabulary: ["comunidad", "vecino"], explanation: "Qué es una comunidad y quiénes la conforman.", sentences: ["Mi comunidad es el lugar donde vivo junto a mis vecinos.", "En la comunidad hay escuelas, parques y tiendas.", "Todos debemos cuidar y respetar nuestra comunidad.", "Ayudar a los vecinos hace la comunidad más feliz."], quizPrompt: "¿Quiénes viven en mi comunidad?", options: [{ label: "Mis vecinos", correct: true }, { label: "Solo mi familia", correct: false }, { label: "Nadie", correct: false }] },
  { subjectKey: "SOCIAL", gradeKey: "PREPRIMARIO", unitTitle: "Símbolos patrios", lessonTitle: "Los símbolos patrios", vocabulary: ["bandera", "escudo", "himno"], explanation: "Los símbolos patrios dominicanos y su significado.", sentences: ["La bandera dominicana tiene los colores azul, rojo y blanco.", "El escudo nacional representa la historia y los valores del país.", "El himno nacional es la canción que representa a la República Dominicana.", "Debemos respetar nuestros símbolos patrios."], quizPrompt: "¿Qué colores tiene la bandera dominicana?", options: [{ label: "Azul, rojo y blanco", correct: true }, { label: "Verde y amarillo", correct: false }, { label: "Negro y gris", correct: false }] },
  { subjectKey: "SOCIAL", gradeKey: "P2", unitTitle: "Mi entorno", lessonTitle: "Mi barrio", vocabulary: ["barrio", "vecino"], explanation: "El barrio como espacio de convivencia cercana.", sentences: ["Mi barrio tiene calles, casas y lugares donde la gente se reúne.", "En mi barrio hay vecinos que se ayudan entre sí.", "Cuidar las calles y los parques mantiene el barrio limpio y agradable.", "Cada barrio tiene su propia historia y tradiciones."], quizPrompt: "¿Qué ayuda a mantener limpio un barrio?", options: [{ label: "Cuidar las calles y parques", correct: true }, { label: "Tirar basura en la calle", correct: false }, { label: "No hacer nada", correct: false }] },
  { subjectKey: "SOCIAL", gradeKey: "P3", unitTitle: "Historia local", lessonTitle: "La historia de mi pueblo", vocabulary: ["historia", "tradición", "raíces"], explanation: "Por qué es importante conocer la historia del propio pueblo o ciudad.", sentences: ["Cada pueblo o ciudad tiene una historia sobre cómo se fundó.", "Conocer la historia de nuestro pueblo nos ayuda a valorar nuestras raíces.", "Los pueblos cambian con el tiempo, pero conservan tradiciones importantes.", "Los abuelos son una buena fuente para aprender sobre la historia local."], quizPrompt: "¿Quiénes son una buena fuente para conocer la historia de un pueblo?", options: [{ label: "Los abuelos", correct: true }, { label: "Los extraterrestres", correct: false }, { label: "Nadie", correct: false }] },
  { subjectKey: "SOCIAL", gradeKey: "P5", unitTitle: "Geografía dominicana", lessonTitle: "La geografía de República Dominicana", vocabulary: ["isla", "montaña", "Pico Duarte"], explanation: "Rasgos geográficos principales de República Dominicana.", sentences: ["República Dominicana está ubicada en la isla La Española, en el mar Caribe.", "El país tiene montañas, valles, ríos y playas.", "El Pico Duarte es la montaña más alta del Caribe.", "La geografía influye en el clima y las actividades de cada región."], quizPrompt: "¿Cuál es la montaña más alta del Caribe?", options: [{ label: "El Pico Duarte", correct: true }, { label: "El Pico Isabel", correct: false }, { label: "El Monte Grande", correct: false }] },

  { subjectKey: "CITIZENSHIP", gradeKey: "PREPRIMARIO", unitTitle: "Convivencia", lessonTitle: "Ser buen compañero", vocabulary: ["compartir", "ayudar"], explanation: "Comportamientos básicos de un buen compañero.", sentences: ["Ser buen compañero significa compartir y ayudar a los demás.", "Cuando alguien se cae, un buen compañero lo ayuda a levantarse.", "Compartir los juguetes hace que todos se diviertan más.", "Tratar a los demás con respeto nos hace mejores amigos."], quizPrompt: "¿Qué hace un buen compañero cuando alguien se cae?", options: [{ label: "Lo ayuda a levantarse", correct: true }, { label: "Se ríe de él", correct: false }, { label: "Se va corriendo", correct: false }] },
  { subjectKey: "CITIZENSHIP", gradeKey: "P3", unitTitle: "Derechos y deberes", lessonTitle: "Los derechos y deberes del niño", vocabulary: ["derecho", "deber"], explanation: "Derechos y deberes básicos de los niños.", sentences: ["Todos los niños tienen derecho a la educación, la salud y el juego.", "Junto a los derechos, también existen deberes, como respetar a los demás.", "Cumplir nuestros deberes ayuda a que todos vivamos mejor juntos.", "Conocer nuestros derechos nos permite defenderlos cuando sea necesario."], quizPrompt: "¿Cuál es un derecho de todos los niños?", options: [{ label: "La educación", correct: true }, { label: "Trabajar todo el día", correct: false }, { label: "No jugar nunca", correct: false }] },
  { subjectKey: "CITIZENSHIP", gradeKey: "S2", unitTitle: "Democracia", lessonTitle: "La democracia y el voto", vocabulary: ["democracia", "voto", "ciudadano"], explanation: "Concepto de democracia y el papel del voto.", sentences: ["La democracia es un sistema donde los ciudadanos eligen a sus representantes por medio del voto.", "Votar es un derecho y también una responsabilidad ciudadana.", "En una democracia, se respetan las opiniones diferentes.", "Participar en la vida democrática fortalece a un país."], quizPrompt: "¿Cómo eligen los ciudadanos a sus representantes en una democracia?", options: [{ label: "Por medio del voto", correct: true }, { label: "Por sorteo", correct: false }, { label: "Por herencia familiar", correct: false }] },

  { subjectKey: "BIBLE", gradeKey: "PREPRIMARIO", unitTitle: "Valores", lessonTitle: "Valores de bondad y compartir", vocabulary: ["bondad", "compartir"], explanation: "Valores de bondad y generosidad presentados de forma sencilla.", sentences: ["Ser bondadoso significa tratar a los demás con amabilidad.", "Compartir lo que tenemos con otros nos hace felices.", "Ayudar a quien lo necesita es un acto de bondad.", "Practicar la bondad todos los días hace del mundo un lugar mejor."], quizPrompt: "¿Qué significa ser bondadoso?", options: [{ label: "Tratar a los demás con amabilidad", correct: true }, { label: "Ignorar a los demás", correct: false }, { label: "Solo pensar en uno mismo", correct: false }] },
  { subjectKey: "BIBLE", gradeKey: "P3", unitTitle: "Valores", lessonTitle: "Historias de valentía y fe", vocabulary: ["valentía", "fe", "esperanza"], explanation: "Valores de valentía y esperanza presentados de forma general.", sentences: ["Muchas historias nos enseñan que la valentía significa hacer lo correcto aunque sea difícil.", "La fe nos ayuda a mantener la esperanza en momentos difíciles.", "Actuar con honestidad y valentía nos ayuda a crecer como personas.", "Estas enseñanzas se han transmitido de generación en generación."], quizPrompt: "¿Qué significa actuar con valentía?", options: [{ label: "Hacer lo correcto aunque sea difícil", correct: true }, { label: "Evitar siempre los retos", correct: false }, { label: "Mentir para evitar problemas", correct: false }] },
  { subjectKey: "BIBLE", gradeKey: "S2", unitTitle: "Ética", lessonTitle: "Ética y valores de vida", vocabulary: ["ética", "honestidad", "responsabilidad"], explanation: "Introducción a la ética y los valores que guían la conducta.", sentences: ["La ética estudia lo que consideramos correcto e incorrecto en nuestras acciones.", "Valores como la honestidad, el respeto y la responsabilidad guían nuestra conducta.", "Vivir según nuestros valores nos ayuda a construir relaciones de confianza.", "Reflexionar sobre nuestras decisiones fortalece nuestro carácter."], quizPrompt: "¿Qué estudia la ética?", options: [{ label: "Lo correcto e incorrecto de nuestras acciones", correct: true }, { label: "Solo las matemáticas", correct: false }, { label: "Los colores del arcoíris", correct: false }] },

  { subjectKey: "DIGITAL", gradeKey: "PREPRIMARIO", unitTitle: "Tecnología segura", lessonTitle: "Uso seguro de la tableta", vocabulary: ["tableta", "permiso"], explanation: "Reglas básicas de uso seguro de dispositivos con apoyo de un adulto.", sentences: ["Usamos la tableta solo con permiso de un adulto.", "Tocamos la pantalla con cuidado y suavidad.", "No compartimos información personal con desconocidos.", "Usar la tecnología con responsabilidad nos mantiene seguros."], quizPrompt: "¿Con quién debemos pedir permiso antes de usar la tableta?", options: [{ label: "Un adulto", correct: true }, { label: "Nadie", correct: false }, { label: "Un desconocido", correct: false }] },
  { subjectKey: "DIGITAL", gradeKey: "P3", unitTitle: "La computadora", lessonTitle: "Partes de la computadora", vocabulary: ["pantalla", "teclado", "ratón"], explanation: "Partes principales de una computadora y su función.", sentences: ["La pantalla muestra las imágenes y el texto de la computadora.", "El teclado se usa para escribir letras y números.", "El ratón nos ayuda a movernos y seleccionar cosas en la pantalla.", "Conocer las partes de la computadora nos ayuda a usarla mejor."], quizPrompt: "¿Qué parte de la computadora se usa para escribir?", options: [{ label: "El teclado", correct: true }, { label: "El ratón", correct: false }, { label: "La pantalla", correct: false }] },
  { subjectKey: "DIGITAL", gradeKey: "S3", unitTitle: "Seguridad digital", lessonTitle: "Seguridad en internet", vocabulary: ["contraseña", "seguridad"], explanation: "Buenas prácticas de seguridad al usar internet.", sentences: ["Nunca debemos compartir contraseñas ni datos personales con desconocidos en internet.", "Es importante verificar la fuente antes de creer o compartir información.", "Usar contraseñas seguras protege nuestras cuentas de intrusos.", "Pensar antes de publicar algo evita problemas futuros."], quizPrompt: "¿Qué no debemos compartir con desconocidos en internet?", options: [{ label: "Contraseñas y datos personales", correct: true }, { label: "Nuestra tarea de matemáticas", correct: false }, { label: "Fotos de paisajes", correct: false }] },

  { subjectKey: "ART", gradeKey: "KINDER", unitTitle: "El color", lessonTitle: "Los colores primarios", vocabulary: ["rojo", "azul", "amarillo"], explanation: "Los colores primarios y cómo se combinan.", sentences: ["Los colores primarios son el rojo, el azul y el amarillo.", "Mezclando colores primarios podemos crear nuevos colores.", "Rojo y amarillo juntos forman el color naranja.", "Pintar con colores primarios es muy divertido."], quizPrompt: "¿Cuáles son los colores primarios?", options: [{ label: "Rojo, azul y amarillo", correct: true }, { label: "Verde, morado y gris", correct: false }, { label: "Negro y blanco", correct: false }] },
  { subjectKey: "ART", gradeKey: "P3", unitTitle: "Formas y figuras", lessonTitle: "Formas y figuras en el arte", vocabulary: ["círculo", "cuadrado", "triángulo"], explanation: "Formas geométricas básicas usadas en el arte.", sentences: ["Los artistas usan formas como círculos, cuadrados y triángulos en sus obras.", "Combinar formas diferentes puede crear dibujos interesantes.", "El color y la forma juntos dan vida a una obra de arte.", "Observar el arte a nuestro alrededor despierta la creatividad."], quizPrompt: "¿Qué forma tiene tres lados?", options: [{ label: "El triángulo", correct: true }, { label: "El círculo", correct: false }, { label: "El cuadrado", correct: false }] },
  { subjectKey: "ART", gradeKey: "S4", unitTitle: "Arte y cultura", lessonTitle: "El arte dominicano", vocabulary: ["artesanía", "identidad cultural"], explanation: "El arte dominicano como expresión de la cultura del país.", sentences: ["El arte dominicano incluye pintura, escultura y artesanía inspiradas en la cultura del país.", "Muchos artistas dominicanos representan el color y la vida cotidiana de la isla en sus obras.", "El arte popular, como las máscaras de carnaval, forma parte de la identidad cultural.", "Conocer el arte dominicano nos conecta con nuestra historia y tradiciones."], quizPrompt: "¿Qué representa el arte dominicano según el texto?", options: [{ label: "La cultura y vida cotidiana del país", correct: true }, { label: "Solo paisajes de otros continentes", correct: false }, { label: "Nada relacionado con la isla", correct: false }] },

  { subjectKey: "PE", gradeKey: "KINDER", unitTitle: "Movimiento", lessonTitle: "Movernos y jugar", vocabulary: ["correr", "saltar"], explanation: "El movimiento y el juego como parte de una vida activa.", sentences: ["Correr, saltar y bailar son formas de ejercitar nuestro cuerpo.", "Jugar afuera nos ayuda a estar fuertes y sanos.", "Es importante tomar agua después de movernos mucho.", "Moverse todos los días nos hace sentir contentos."], quizPrompt: "¿Qué debemos tomar después de movernos mucho?", options: [{ label: "Agua", correct: true }, { label: "Nada", correct: false }, { label: "Solo dulces", correct: false }] },
  { subjectKey: "PE", gradeKey: "P3", unitTitle: "Ejercicio seguro", lessonTitle: "El calentamiento antes de hacer ejercicio", vocabulary: ["calentamiento", "estirar"], explanation: "Por qué es importante calentar antes de hacer ejercicio.", sentences: ["Calentar el cuerpo antes de hacer ejercicio prepara los músculos para moverse.", "Estirar los brazos y las piernas ayuda a evitar lesiones.", "Un buen calentamiento dura unos minutos antes de la actividad principal.", "Cuidar nuestro cuerpo nos permite jugar y hacer deporte de forma segura."], quizPrompt: "¿Para qué sirve el calentamiento antes de hacer ejercicio?", options: [{ label: "Para preparar los músculos y evitar lesiones", correct: true }, { label: "Para cansarse más rápido", correct: false }, { label: "No sirve para nada", correct: false }] },
  { subjectKey: "PE", gradeKey: "S2", unitTitle: "Vida saludable", lessonTitle: "Hábitos de vida saludable", vocabulary: ["alimentación", "descanso"], explanation: "Hábitos que contribuyen a una vida saludable.", sentences: ["Una vida saludable incluye buena alimentación, ejercicio regular y suficiente descanso.", "Comer frutas y vegetales aporta vitaminas importantes para el cuerpo.", "Dormir lo suficiente ayuda a la concentración y al buen ánimo.", "Mantener hábitos saludables mejora nuestra calidad de vida a largo plazo."], quizPrompt: "¿Qué aportan las frutas y vegetales al cuerpo?", options: [{ label: "Vitaminas importantes", correct: true }, { label: "Solo azúcar", correct: false }, { label: "Nada beneficioso", correct: false }] },

  { subjectKey: "RELIGIOUS", gradeKey: "KINDER", unitTitle: "Valores humanos", lessonTitle: "Ser agradecido", vocabulary: ["gratitud", "gracias"], explanation: "El valor de la gratitud en la vida diaria.", sentences: ["Decir 'gracias' es una forma de mostrar aprecio por los demás.", "Ser agradecido nos ayuda a valorar lo que tenemos.", "Podemos agradecer a nuestra familia, amigos y maestros.", "La gratitud nos hace sentir más felices."], quizPrompt: "¿Qué palabra mostramos cuando somos agradecidos?", options: [{ label: "Gracias", correct: true }, { label: "Nunca", correct: false }, { label: "Después", correct: false }] },
  { subjectKey: "RELIGIOUS", gradeKey: "P3", unitTitle: "Convivencia", lessonTitle: "El respeto a los demás", vocabulary: ["respeto", "escuchar"], explanation: "El respeto como base de la buena convivencia.", sentences: ["Respetar a los demás significa tratarlos con consideración y buena actitud.", "Escuchar a otra persona sin interrumpir es una muestra de respeto.", "El respeto también incluye aceptar las diferencias entre las personas.", "Cuando nos respetamos, es más fácil convivir en paz."], quizPrompt: "¿Qué es una muestra de respeto hacia los demás?", options: [{ label: "Escuchar sin interrumpir", correct: true }, { label: "Gritar más fuerte", correct: false }, { label: "Ignorar a la persona", correct: false }] },
  { subjectKey: "RELIGIOUS", gradeKey: "S1", unitTitle: "Valores universales", lessonTitle: "Valores universales y convivencia", vocabulary: ["justicia", "solidaridad", "convivencia"], explanation: "Valores compartidos por muchas culturas y su papel en la convivencia.", sentences: ["Valores como la honestidad, la justicia y la solidaridad son reconocidos en muchas culturas del mundo.", "Estos valores ayudan a las personas a convivir de manera pacífica.", "Practicar estos valores en la vida diaria fortalece a la comunidad.", "La convivencia armoniosa se construye con respeto mutuo."], quizPrompt: "¿Qué ayuda a construir la convivencia armoniosa?", options: [{ label: "El respeto mutuo", correct: true }, { label: "La indiferencia", correct: false }, { label: "El egoísmo", correct: false }] },

  { subjectKey: "SEL", gradeKey: "PREPRIMARIO", unitTitle: "Mis emociones", lessonTitle: "Reconocer mis emociones", vocabulary: ["alegría", "tristeza", "emoción"], explanation: "Identificar y nombrar las emociones básicas.", sentences: ["A veces sentimos alegría, tristeza, miedo o enojo.", "Todas las emociones son normales y está bien sentirlas.", "Podemos hablar sobre cómo nos sentimos con un adulto de confianza.", "Reconocer nuestras emociones nos ayuda a entendernos mejor."], quizPrompt: "¿Qué podemos hacer cuando sentimos una emoción fuerte?", options: [{ label: "Hablar con un adulto de confianza", correct: true }, { label: "Guardarlo todo en silencio siempre", correct: false }, { label: "Ignorarlo por completo", correct: false }] },
  { subjectKey: "SEL", gradeKey: "P3", unitTitle: "Resolución de conflictos", lessonTitle: "Resolver conflictos con calma", vocabulary: ["conflicto", "calma", "solución"], explanation: "Pasos sencillos para resolver un desacuerdo con calma.", sentences: ["Cuando tenemos un desacuerdo con alguien, respirar profundo nos ayuda a calmarnos.", "Escuchar el punto de vista del otro es el primer paso para resolver un conflicto.", "Buscar una solución justa para ambas partes evita que el problema crezca.", "Pedir ayuda a un adulto es una buena opción si el conflicto es difícil de resolver."], quizPrompt: "¿Qué nos ayuda a calmarnos durante un desacuerdo?", options: [{ label: "Respirar profundo", correct: true }, { label: "Gritar más fuerte", correct: false }, { label: "Salir corriendo sin hablar", correct: false }] },
  { subjectKey: "SEL", gradeKey: "S3", unitTitle: "Bienestar emocional", lessonTitle: "El manejo del estrés", vocabulary: ["estrés", "respiración", "descanso"], explanation: "Estrategias sencillas para manejar el estrés cotidiano.", sentences: ["El estrés es una reacción natural del cuerpo ante situaciones difíciles.", "Técnicas como la respiración profunda y el ejercicio ayudan a reducir el estrés.", "Organizar el tiempo y descansar lo suficiente también disminuye la tensión.", "Hablar sobre lo que sentimos con alguien de confianza alivia el estrés."], quizPrompt: "¿Qué técnica ayuda a reducir el estrés?", options: [{ label: "La respiración profunda", correct: true }, { label: "Ignorar el problema para siempre", correct: false }, { label: "No dormir nunca", correct: false }] },

  { subjectKey: "ENGLISH", gradeKey: "PREPRIMARIO", unitTitle: "Colors and numbers", lessonTitle: "Colors and numbers", vocabulary: ["red", "blue", "yellow"], explanation: "Basic color and number vocabulary in English.", sentences: ["Red, blue, and yellow are colors.", "One, two, three, four, five.", "I see a red apple.", "I can count to five."], quizPrompt: "What color is the apple?", options: [{ label: "Red", correct: true }, { label: "Blue", correct: false }, { label: "Green", correct: false }] },
  { subjectKey: "ENGLISH", gradeKey: "P3", unitTitle: "Daily routines", lessonTitle: "My daily routine", vocabulary: ["wake up", "breakfast", "school"], explanation: "Simple present tense vocabulary describing a daily routine.", sentences: ["I wake up every morning and brush my teeth.", "Then I eat breakfast with my family.", "After breakfast, I go to school.", "In the evening, I do my homework and go to sleep."], quizPrompt: "What does the person do after breakfast?", options: [{ label: "Go to school", correct: true }, { label: "Go to sleep", correct: false }, { label: "Brush teeth", correct: false }] },
  { subjectKey: "ENGLISH", gradeKey: "S4", unitTitle: "Future tense", lessonTitle: "Talking about the future", vocabulary: ["will", "going to", "plan"], explanation: "Using 'will' and 'going to' to talk about the future.", sentences: ["We use 'will' to talk about future plans and predictions.", "For example, 'I will study tomorrow' talks about a plan.", "We can also use 'going to' for plans we have already decided.", "Practicing future tense helps us talk about our goals."], quizPrompt: "Which word do we use to talk about future plans?", options: [{ label: "Will", correct: true }, { label: "Was", correct: false }, { label: "Did", correct: false }] },
];

const bulkLessons: BulkLesson[] = RAW.map((r) => ({
  subjectCode: r.subjectKey,
  gradeName: GRADE_NAME[r.gradeKey],
  unitTitle: r.unitTitle,
  lessonTitle: r.lessonTitle,
  vocabulary: r.vocabulary,
  explanation: r.explanation,
  sentences: r.sentences,
  isStory: STORY_GRADES.has(r.gradeKey),
  quizPrompt: r.quizPrompt,
  options: r.options,
  recommendedAge: RECOMMENDED_AGE[r.gradeKey],
}));

async function main() {
  const schoolAdmin = await prisma.user.findUniqueOrThrow({ where: { email: "admin@estudiard.demo" } });
  const subjects = await prisma.subject.findMany();
  const grades = await prisma.grade.findMany();
  const subjectByCode = new Map(subjects.map((s) => [s.code, s]));
  const gradeByName = new Map(grades.map((g) => [g.name, g]));

  let created = 0;
  let skipped = 0;

  for (const bl of bulkLessons) {
    const subject = subjectByCode.get(bl.subjectCode);
    const grade = gradeByName.get(bl.gradeName);
    if (!subject || !grade) {
      console.warn(`Skipping "${bl.lessonTitle}" — subject or grade not found.`);
      continue;
    }

    const existing = await prisma.lesson.findFirst({ where: { title: bl.lessonTitle, unit: { gradeId: grade.id, subjectId: subject.id } } });
    if (existing) {
      skipped++;
      continue;
    }

    const unit = await prisma.unit.create({
      data: { subjectId: subject.id, gradeId: grade.id, title: bl.unitTitle, order: 1 },
    });
    const lesson = await prisma.lesson.create({
      data: {
        unitId: unit.id,
        title: bl.lessonTitle,
        recommendedAge: bl.recommendedAge,
        objectives: [bl.explanation],
        prerequisites: [],
        vocabulary: bl.vocabulary,
        explanation: bl.explanation,
        accessibilityNotes: "Compatible con lectura de pantalla, alto contraste y narración por voz.",
        teacherNotes: "Lección de demostración revisada para el prototipo Fase 1.",
        parentExtension: "Comenta con tu hijo/a lo que aprendió usando ejemplos de la vida diaria.",
        sourceAttribution: "Estudia RD — contenido de demostración, Fase 1.",
        status: "PUBLISHED",
        publishedAt: new Date(),
        authorId: schoolAdmin.id,
        order: 1,
      },
    });
    for (const [from, to] of [
      ["DRAFT", "ACADEMIC_REVIEW"],
      ["ACADEMIC_REVIEW", "SAFETY_REVIEW"],
      ["SAFETY_REVIEW", "APPROVED"],
      ["APPROVED", "PUBLISHED"],
    ] as const) {
      await prisma.contentApproval.create({ data: { lessonId: lesson.id, fromStatus: from, toStatus: to, reviewerId: schoolAdmin.id } });
    }
    const competency = await prisma.competency.create({
      data: { subjectId: subject.id, gradeId: grade.id, type: "FUNDAMENTAL", description: bl.explanation },
    });
    await prisma.lessonCompetency.create({ data: { lessonId: lesson.id, competencyId: competency.id } });

    if (bl.isStory) {
      await prisma.activity.create({
        data: { lessonId: lesson.id, type: "NARRATED_STORY", title: "Cuento", order: 1, content: { sentences: bl.sentences } },
      });
    } else {
      const passage = bl.sentences.join(" ");
      await prisma.activity.create({
        data: { lessonId: lesson.id, type: "READING_PASSAGE", title: "Lee el texto", order: 1, content: { passage, words: passage.split(" ") } },
      });
    }

    const quiz = await prisma.activity.create({
      data: { lessonId: lesson.id, type: "QUIZ", title: "¿Qué aprendiste?", order: 2, content: {} },
    });
    const question = await prisma.question.create({
      data: { activityId: quiz.id, prompt: bl.quizPrompt, order: 1, explanation: null },
    });
    await prisma.answerOption.createMany({
      data: bl.options.map((o, i) => ({ questionId: question.id, label: o.label, isCorrect: o.correct, order: i + 1 })),
    });

    created++;
  }

  console.log(`Bulk lesson expansion complete. Created ${created} lessons, skipped ${skipped} (already existed).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
